-- KPI 스코어카드 (Number). 스코어카드 4개는 이 쿼리를 복제해 카드별 컬럼 1개만 남긴다.
WITH va AS (
  SELECT AGENT_ID, VENDOR_ID
  FROM VROONG.RAW_VENDORSET.VENDOR_AGENTS
  WHERE IS_DELETED = '0'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY AGENT_ID ORDER BY ACTIVATED_AT DESC NULLS LAST) = 1
)
SELECT
  COUNT(*) AS "총물량",
  ROUND(COUNT_IF(o.ORDER_STATUS='취소') / NULLIF(COUNT(*),0) * 100, 2) AS "취소율",
  ROUND(COUNT_IF(o.ORDER_STATUS='배달완료' AND o.COMPLETE_TIME<=2400)
        / NULLIF(COUNT_IF(o.ORDER_STATUS='배달완료'),0) * 100, 1) AS "완료율_40분",
  MAX(o.PARTITIONAL_DATE) AS "데이터기준일"
FROM VROONG.DATAMART.ORDERS o
JOIN va ON TO_VARCHAR(o.AGENT_ID) = va.AGENT_ID
JOIN VROONG.RAW_VENDORSET.VENDORS v ON va.VENDOR_ID = v.ID
 AND v.BUSINESS_NAME NOT ILIKE '%QA%' AND v.BUSINESS_NAME NOT ILIKE '%테스트%' AND v.BUSINESS_NAME NOT ILIKE '%test%'
LEFT JOIN VROONG.RAW_SALESMANAGEMENT.ZONES z ON v.ZONE_UUID = z.UUID
WHERE 1=1
  [[AND z.ZONE_NAME = {{zone}}]]
  [[AND o.SUBMITTED_AT >= {{start_date}}]]
  [[AND o.SUBMITTED_AT < DATEADD(day, 1, {{end_date}})]]
