-- A1. 물량 트렌드 (일/주 토글, 물량타입 분해) — Bar(Stacked). 권역 기준, 오더 생성(CREATED_AT) 시점.
SELECT
  DATE_TRUNC({{granularity}}, o.CREATED_AT) AS "기간",
  CASE
    WHEN s.SALES_TYPE='직영센터' THEN 'G4'
    WHEN s.MANAGEMENT_TYPE='요기요OD' THEN 'OD'
    WHEN s.MANAGEMENT_TYPE='메쉬프라임' THEN '법인'
    WHEN s.MANAGEMENT_TYPE='로컬세일즈' THEN '로컬'
    ELSE '기타'
  END AS "물량타입",
  COUNT(*) AS "물량"
FROM VROONG.DATAMART.ORDERS o
JOIN VROONG.RAW_SALESMANAGEMENT.ZONES z
  ON TO_VARCHAR(o.MONITORING_PARTNER_ID) = z.EXTERNAL_PARTNER_ID AND z.IS_ACTIVE = '1'
LEFT JOIN VROONG.DATAMART.STORES s ON o.STORE_ID = s.STORE_ID
WHERE z.ZONE_NAME NOT ILIKE '%QA%' AND z.ZONE_NAME NOT ILIKE '%테스트%' AND z.ZONE_NAME NOT ILIKE '%test%'
  [[AND z.ZONE_NAME = {{zone}}]]
  [[AND o.CREATED_AT >= {{start_date}}]]
  [[AND o.CREATED_AT < DATEADD(day, 1, {{end_date}})]]
GROUP BY 1, 2
ORDER BY 1, 2
