-- A1. 물량 트렌드 (일/주 토글, 물량타입 분해) — Bar(Stacked). X=기간, Y=물량, Series=물량타입
WITH va AS (
  SELECT AGENT_ID, VENDOR_ID FROM VROONG.RAW_VENDORSET.VENDOR_AGENTS
  WHERE IS_DELETED = '0'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY AGENT_ID ORDER BY ACTIVATED_AT DESC NULLS LAST) = 1
)
SELECT
  DATE_TRUNC({{granularity}}, o.SUBMITTED_AT) AS "기간",
  CASE
    WHEN s.MANAGEMENT_TYPE='요기요OD' THEN 'OD'
    WHEN s.MANAGEMENT_TYPE='메쉬프라임' THEN '법인'
    WHEN s.MANAGEMENT_TYPE='로컬세일즈' AND s.SALES_TYPE='직영센터' THEN 'G4'
    WHEN s.MANAGEMENT_TYPE='로컬세일즈' THEN '로컬'
    ELSE '기타'
  END AS "물량타입",
  COUNT(*) AS "물량"
FROM VROONG.DATAMART.ORDERS o
JOIN va ON TO_VARCHAR(o.AGENT_ID) = va.AGENT_ID
JOIN VROONG.RAW_VENDORSET.VENDORS v ON va.VENDOR_ID = v.ID
 AND v.BUSINESS_NAME NOT ILIKE '%QA%' AND v.BUSINESS_NAME NOT ILIKE '%테스트%' AND v.BUSINESS_NAME NOT ILIKE '%test%'
LEFT JOIN VROONG.RAW_SALESMANAGEMENT.ZONES z ON v.ZONE_UUID = z.UUID
LEFT JOIN VROONG.DATAMART.STORES s ON o.STORE_ID = s.STORE_ID
WHERE 1=1
  [[AND z.ZONE_NAME = {{zone}}]]
  [[AND o.SUBMITTED_AT >= {{start_date}}]]
  [[AND o.SUBMITTED_AT < DATEADD(day, 1, {{end_date}})]]
GROUP BY 1, 2
ORDER BY 1, 2
