-- A3. 시간대별 물량 (일평균 패턴) — Bar. 권역 기준, 오더 생성(CREATED_AT) 시각.
SELECT
  HOUR(o.CREATED_AT) AS "시",
  COUNT(*) / NULLIF(COUNT(DISTINCT o.CREATED_AT::date), 0) AS "일평균물량"
FROM VROONG.DATAMART.ORDERS o
JOIN VROONG.RAW_SALESMANAGEMENT.ZONES z
  ON TO_VARCHAR(o.MONITORING_PARTNER_ID) = z.EXTERNAL_PARTNER_ID AND z.IS_ACTIVE = '1'
WHERE z.ZONE_NAME NOT ILIKE '%QA%' AND z.ZONE_NAME NOT ILIKE '%테스트%' AND z.ZONE_NAME NOT ILIKE '%test%'
  [[AND z.ZONE_NAME = {{zone}}]]
  [[AND o.CREATED_AT >= {{start_date}}]]
  [[AND o.CREATED_AT < DATEADD(day, 1, {{end_date}})]]
GROUP BY 1
ORDER BY 1
