-- A3. 시간대별 물량 (일평균 패턴) — Bar. X=시, Y=일평균물량
WITH va AS (
  SELECT AGENT_ID, VENDOR_ID FROM VROONG.RAW_VENDORSET.VENDOR_AGENTS
  WHERE IS_DELETED = '0'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY AGENT_ID ORDER BY ACTIVATED_AT DESC NULLS LAST) = 1
)
SELECT
  HOUR(o.SUBMITTED_AT) AS "시",
  COUNT(*) / NULLIF(COUNT(DISTINCT o.PARTITIONAL_DATE), 0) AS "일평균물량"
FROM VROONG.DATAMART.ORDERS o
JOIN va ON TO_VARCHAR(o.AGENT_ID) = va.AGENT_ID
JOIN VROONG.RAW_VENDORSET.VENDORS v ON va.VENDOR_ID = v.ID
 AND v.BUSINESS_NAME NOT ILIKE '%QA%' AND v.BUSINESS_NAME NOT ILIKE '%테스트%' AND v.BUSINESS_NAME NOT ILIKE '%test%'
LEFT JOIN VROONG.RAW_SALESMANAGEMENT.ZONES z ON v.ZONE_UUID = z.UUID
WHERE 1=1
  [[AND z.ZONE_NAME = {{zone}}]]
  [[AND o.SUBMITTED_AT >= {{start_date}}]]
  [[AND o.SUBMITTED_AT < DATEADD(day, 1, {{end_date}})]]
GROUP BY 1
ORDER BY 1
