-- B3. 프렌즈 vs 벤더 수행 비율 — Pie/Row. Dim=수행유형, Measure=건수, % 표시
WITH va AS (
  SELECT AGENT_ID, VENDOR_ID FROM VROONG.RAW_VENDORSET.VENDOR_AGENTS
  WHERE IS_DELETED = '0'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY AGENT_ID ORDER BY ACTIVATED_AT DESC NULLS LAST) = 1
)
SELECT
  CASE WHEN o.IS_VROONG_FRIENDS_ORDER THEN '프렌즈(DP-F)' ELSE '벤더세트(DP-S)' END AS "수행유형",
  COUNT(*) AS "건수"
FROM VROONG.DATAMART.ORDERS o
JOIN va ON TO_VARCHAR(o.AGENT_ID) = va.AGENT_ID
JOIN VROONG.RAW_VENDORSET.VENDORS v ON va.VENDOR_ID = v.ID
 AND v.BUSINESS_NAME NOT ILIKE '%QA%' AND v.BUSINESS_NAME NOT ILIKE '%테스트%' AND v.BUSINESS_NAME NOT ILIKE '%test%'
LEFT JOIN VROONG.RAW_SALESMANAGEMENT.ZONES z ON v.ZONE_UUID = z.UUID
WHERE 1=1
  [[AND z.ZONE_NAME = {{zone}}]]
  [[AND o.SUBMITTED_AT >= {{start_date}}]]
  [[AND o.SUBMITTED_AT < DATEADD(day, 1, {{end_date}})]]
GROUP BY 1
