-- B4+B5. 프렌즈·벤더 40분 완료율 (2시리즈 통합) — Line. Series=수행유형
WITH va AS (
  SELECT AGENT_ID, VENDOR_ID FROM VROONG.RAW_VENDORSET.VENDOR_AGENTS
  WHERE IS_DELETED = '0'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY AGENT_ID ORDER BY ACTIVATED_AT DESC NULLS LAST) = 1
)
SELECT
  DATE_TRUNC({{granularity}}, o.SUBMITTED_AT) AS "기간",
  CASE WHEN o.IS_VROONG_FRIENDS_ORDER THEN '프렌즈' ELSE '벤더세트' END AS "수행유형",
  ROUND(COUNT_IF(o.ORDER_STATUS='배달완료' AND o.COMPLETE_TIME<=2400)
        / NULLIF(COUNT_IF(o.ORDER_STATUS='배달완료'),0) * 100, 1) AS "완료율_40분"
FROM VROONG.DATAMART.ORDERS o
JOIN va ON TO_VARCHAR(o.AGENT_ID) = va.AGENT_ID
JOIN VROONG.RAW_VENDORSET.VENDORS v ON va.VENDOR_ID = v.ID
 AND v.BUSINESS_NAME NOT ILIKE '%QA%' AND v.BUSINESS_NAME NOT ILIKE '%테스트%' AND v.BUSINESS_NAME NOT ILIKE '%test%'
LEFT JOIN VROONG.RAW_SALESMANAGEMENT.ZONES z ON v.ZONE_UUID = z.UUID
WHERE 1=1
  [[AND z.ZONE_NAME = {{zone}}]]
  [[AND o.SUBMITTED_AT >= {{start_date}}]]
  [[AND o.SUBMITTED_AT < DATEADD(day, 1, {{end_date}})]]
GROUP BY 1, 2
ORDER BY 1, 2
